title: "OCTAve: 2D en face Optical Coherence Tomography Angiography Vessel Segmentation in Weakly-Supervised Learning with Locality Augmentation"
description: "Amrest Chinkamol, Vetit Kanjaras, Phattarapong Sawangjai, Yitian Zhao, Thapanun Sudhawiyangkul, Chantana Chantrapornchai, Cuntai Guan, Theerawit Wilaiprasitporn"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

details:
  arxiv: https://arxiv.org/abs/2207.12238
  journal_name: IEEE Transactions on Biomedical Engineering
  journal_link: https://doi.org/10.1109/TBME.2022.3232102

show_downloads: true